default_platform(:ios)

platform :ios do

  all_main_test_target = [
  ]

  all_arhive_target = [
    [ "Xcode 11.0", "./Archive/Xcode11.0/xcode11.0.xcodeproj", "xcode11.0AllTests" ],
    [ "Xcode 11.4", "./Archive/Xcode11.4/xcode11.4.xcodeproj", "xcode11.4" ],
    [ "Xcode 12.5", "./Archive/Xcode12.5/xcode12.5.xcodeproj", "Xcode12.5" ],
  ]

  desc "run main tests"
  lane :main_tests do
    all_main_test_target.each do |xcode_version, project, scheme|
      UI.message("---------------------------------")
      UI.message("Running tests for #{xcode_version}")

      run_tests(
        project: project,
        scheme: scheme,
        result_bundle: true
      )
    end
  end


  desc "run all tests"
  lane :all_tests do
    all_test_target = all_main_test_target.concat(all_arhive_target)
    all_test_target.each do |xcode_version, project, scheme|
      UI.message("---------------------------------")
      UI.message("Running tests for #{xcode_version}")

      run_tests(
        project: project,
        scheme: scheme,
        result_bundle: true
      )
    end
  end

end
