name: All Xcode Versions Test

on: 
  push:
    branches:
      - main

env:
  DEVELOPER_DIR: /Applications/Xcode_16.3.0.app

jobs:
  all_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Cache bundle directory
      uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: setup
      run: |
        cd ./Samples
        brew reinstall xcbeautify
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: run all test
      run: |
        cd ./Samples
        bundle exec fastlane main_tests
