name: All Xcode Versions Test

on: 
  push:
    branches:
      - main

jobs:
  all_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache bundle directory
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
            ${{ runner.os }}-gem-
    - name: setup
      run: |
        cd ./Samples
        brew reinstall xcbeautify
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: run all test
      run: |
        cd ./Samples
        bundle exec fastlane all_tests
